### ISSUE TITLE
no link for downing dataset LEVIR-PL, SYSU-PL, and GLVM-PL

### ISSUE THREAD

**Issue by aiyeshi** [guanyuezhen/MS-Former#1]
Hi,
I found the BCDD-PL has the same link downloading address for  dataset LEVIR-PL, SYSU-PL, and GLVM-PL.
Could you provide the link for downing dataset LEVIR-PL, SYSU-PL, and GLVM-PL?

**Comment by guanyuezhen** [comment]
> Hi, I found the BCDD-PL has the same link downloading address for dataset LEVIR-PL, SYSU-PL, and GLVM-PL. Could you provide the link for downing dataset LEVIR-PL, SYSU-PL, and GLVM-PL?

I have implemented a function in ./datasets/dataset.py to convert labels into patch labels. You can use LEVIR and SYSU datasets to perform experiments directly.
